# Generated by Django 5.2.17 on 2026-09-23 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], max_length=8)),
                ('scope', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('generating', 'Generating'), ('available', 'Available'), ('failed', 'Failed'), ('expired', 'Expired')], default='requested', max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200)),
                ('case', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='cases.case')),
                ('requested_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='requested_reports', to=settings.AUTH_USER_MODEL)),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='tasks.taskrun')),
            ],
            options={
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='ix_reporting_report_requested_by_time'), models.Index(condition=models.Q(('status', 'available')), fields=['expires_at'], name='ix_reporting_report_expiry')],
                'constraints': [models.UniqueConstraint(fields=('public_id',), name='uq_reporting_report_public_id'), models.UniqueConstraint(fields=('storage_key',), name='uq_reporting_report_storage_key'), models.CheckConstraint(condition=models.Q(('format__in', ['pdf', 'csv', 'json'])), name='ck_reporting_report_format_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['requested', 'generating', 'available', 'failed', 'expired'])), name='ck_reporting_report_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'available'), _negated=True), models.Q(('sha256__isnull', False), ('storage_key__isnull', False)), _connector='OR'), name='ck_reporting_report_available_has_object'), models.CheckConstraint(condition=models.Q(('sha256__isnull', True), ('sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='ck_reporting_report_sha256_hex')],
            },
        ),
    ]
