# Generated by Django 5.2.17 on 2026-09-23 16:35

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('search', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('closed', 'Closed')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='owned_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('contribute', 'Contribute'), ('review', 'Review')], max_length=16)),
                ('granted_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='cases.case')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_memberships', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='case_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('sequence', models.IntegerField()),
                ('query_type', models.CharField(choices=[('image', 'Image'), ('text', 'Text')], max_length=8)),
                ('query_text', models.TextField(blank=True, null=True)),
                ('preprocessing', models.CharField(choices=[('none', 'None'), ('histogram_equalisation', 'Histogram equalisation')], default='none', max_length=24)),
                ('routed_spectrum', models.CharField(blank=True, choices=[('visible', 'Visible'), ('infrared', 'Infrared')], max_length=16, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('encoding', 'Encoding'), ('searching', 'Searching'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('result_count', models.IntegerField(default=0)),
                ('probe_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='probe_queries', to='datasets.contentobject')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queries', to='tasks.taskrun')),
            ],
            options={
                'verbose_name_plural': 'queries',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('rank', models.IntegerField()),
                ('score_fused', models.FloatField()),
                ('score_model', models.FloatField()),
                ('score_clip', models.FloatField(blank=True, null=True)),
                ('score_dinov2', models.FloatField(blank=True, null=True)),
                ('score_metadata', models.FloatField(blank=True, null=True)),
                ('evidence_file', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='datasets.evidencefile')),
                ('query', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='cases.query')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=200)),
                ('model_weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('metadata_weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('top_k', models.IntegerField()),
                ('overfetch_factor', models.IntegerField(default=6)),
                ('overfetch_ceiling', models.IntegerField(default=500)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='cases.case')),
                ('clip_encoder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clip_runs', to='search.encoder')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_runs', to=settings.AUTH_USER_MODEL)),
                ('dinov2_encoder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dinov2_runs', to='search.encoder')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retrieval_runs', to='tasks.taskrun')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='run',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='queries', to='cases.run'),
        ),
        migrations.CreateModel(
            name='RunCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_restrictions', to='datasets.corpus')),
                ('run', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to='cases.run')),
            ],
            options={
                'verbose_name_plural': 'run corpora',
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['owner', 'status'], name='ix_cases_case_owner_status'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-opened_at'], name='ix_cases_case_status_opened'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uq_cases_case_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('public_id',), name='uq_cases_case_public_id'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'under_review', 'closed'])), name='ck_cases_case_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status', 'closed')), models.Q(models.Q(('status', 'closed'), _negated=True), ('closed_at__isnull', True)), _connector='OR'), name='ck_cases_case_closed_at_paired'),
        ),
        migrations.AddIndex(
            model_name='casemembership',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user', 'case'], name='ix_cases_casemembership_user_active'),
        ),
        migrations.AddIndex(
            model_name='casemembership',
            index=models.Index(fields=['case'], name='ix_cases_casemembership_case'),
        ),
        migrations.AddConstraint(
            model_name='casemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('case', 'user'), name='uq_cases_casemembership_active'),
        ),
        migrations.AddConstraint(
            model_name='casemembership',
            constraint=models.CheckConstraint(condition=models.Q(('access_level__in', ['read', 'contribute', 'review'])), name='ck_cases_casemembership_access_valid'),
        ),
        migrations.AddConstraint(
            model_name='casemembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False)), _connector='OR'), name='ck_cases_casemembership_revocation_pair'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['evidence_file'], name='ix_cases_result_evidence_file'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('query', 'rank'), name='uq_cases_result_query_rank'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('query', 'evidence_file'), name='uq_cases_result_query_file'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('public_id',), name='uq_cases_result_public_id'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='ck_cases_result_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('score_fused__gte', -1), ('score_fused__lte', 1), ('score_model__gte', -1), ('score_model__lte', 1), models.Q(('score_clip__isnull', True), models.Q(('score_clip__gte', -1), ('score_clip__lte', 1)), _connector='OR'), models.Q(('score_dinov2__isnull', True), models.Q(('score_dinov2__gte', -1), ('score_dinov2__lte', 1)), _connector='OR'), models.Q(('score_metadata__isnull', True), models.Q(('score_metadata__gte', -1), ('score_metadata__lte', 1)), _connector='OR')), name='ck_cases_result_scores_range'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('score_clip__isnull', False), ('score_dinov2__isnull', False), _connector='OR'), name='ck_cases_result_at_least_one_model_score'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['case', '-created_at'], name='ix_cases_run_case_created'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'running'])), fields=['status'], name='ix_cases_run_status_pending'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('case', 'label'), name='uq_cases_run_case_label'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('public_id',), name='uq_cases_run_public_id'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.CheckConstraint(condition=models.Q(('model_weight__gte', 0), ('model_weight__lte', 1), ('metadata_weight__gte', 0), ('metadata_weight__lte', 1)), name='ck_cases_run_weights_range'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.CheckConstraint(condition=models.Q(('top_k__gte', 1), ('top_k__lte', 500)), name='ck_cases_run_top_k_range'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.CheckConstraint(condition=models.Q(('overfetch_factor__gte', 1), ('overfetch_factor__lte', 20), ('overfetch_ceiling__gte', 1), ('overfetch_ceiling__lte', 5000)), name='ck_cases_run_overfetch_sane'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'complete', 'failed', 'cancelled'])), name='ck_cases_run_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.CheckConstraint(condition=models.Q(('clip_encoder__isnull', False), ('dinov2_encoder__isnull', False), _connector='OR'), name='ck_cases_run_encoder_present'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uq_cases_query_run_sequence'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.UniqueConstraint(fields=('public_id',), name='uq_cases_query_public_id'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('probe_content__isnull', False), ('query_text__isnull', True), ('query_type', 'image')), models.Q(('probe_content__isnull', True), ('query_text__isnull', False), ('query_type', 'text')), _connector='OR'), name='ck_cases_query_type_payload'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.CheckConstraint(condition=models.Q(('query_text__isnull', True), models.Q(('query_text__length__gte', 1), ('query_text__length__lte', 2000)), _connector='OR'), name='ck_cases_query_text_length'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'encoding', 'searching', 'complete', 'failed'])), name='ck_cases_query_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='runcorpus',
            constraint=models.UniqueConstraint(fields=('run', 'corpus'), name='uq_cases_runcorpus_run_corpus'),
        ),
    ]
