# Generated by Django 5.2.17 on 2026-09-23 16:46

import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_type', models.CharField(choices=[('priority', 'Priority'), ('status', 'Status'), ('custom', 'Custom')], max_length=16)),
                ('label', models.CharField(max_length=100)),
                ('colour', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tag_type', 'label'), name='uq_review_tag_type_label'), models.CheckConstraint(condition=models.Q(('tag_type__in', ['priority', 'status', 'custom'])), name='ck_review_tag_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('countersigned', 'Countersigned'), ('withdrawn', 'Withdrawn')], default='requested', max_length=16)),
                ('evidence_label', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('countersigned_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('countersigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countersigned_approvals', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='cases.result')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'requested_at'], name='ix_review_approval_state'), models.Index(fields=['decided_by', '-decided_at'], name='ix_review_approval_decided_by')],
                'constraints': [models.UniqueConstraint(fields=('result',), name='uq_review_approval_result'), models.UniqueConstraint(fields=('public_id',), name='uq_review_approval_public_id'), models.CheckConstraint(condition=models.Q(('state__in', ['requested', 'approved', 'rejected', 'countersigned', 'withdrawn'])), name='ck_review_approval_state_valid'), models.CheckConstraint(condition=models.Q(('state', 'requested'), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False)), _connector='OR'), name='ck_review_approval_decision_paired'), models.CheckConstraint(condition=models.Q(models.Q(('countersigned_at__isnull', True), ('countersigned_by__isnull', True)), models.Q(('countersigned_at__isnull', False), ('countersigned_by__isnull', False)), _connector='OR'), name='ck_review_approval_countersign_paired'), models.CheckConstraint(condition=models.Q(('countersigned_by__isnull', True), models.Q(('countersigned_by', models.F('decided_by')), _negated=True), _connector='OR'), name='ck_review_approval_no_self_countersign'), models.CheckConstraint(condition=models.Q(('countersigned_by__isnull', True), ('decided_by__isnull', False), _connector='OR'), name='ck_review_approval_countersign_requires_decision'), models.CheckConstraint(condition=models.Q(models.Q(('withdrawn_at__isnull', True), ('withdrawn_by__isnull', True)), models.Q(('withdrawn_at__isnull', False), ('withdrawn_by__isnull', False)), _connector='OR'), name='ck_review_approval_withdrawal_paired')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('scope', models.CharField(choices=[('case', 'Case'), ('run', 'Run'), ('query', 'Query'), ('result', 'Result')], max_length=8)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.case')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='review.note')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.query')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.result')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.run')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='review.note')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(condition=models.Q(('result__isnull', False), ('superseded_by__isnull', True)), fields=['result', '-created_at'], name='ix_review_note_result_current'), models.Index(condition=models.Q(('case__isnull', False), ('is_pinned', True)), fields=['case'], name='ix_review_note_case_pinned')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('case__isnull', False), ('scope', 'case'), ('run__isnull', True), ('query__isnull', True), ('result__isnull', True)), models.Q(('run__isnull', False), ('scope', 'run'), ('case__isnull', True), ('query__isnull', True), ('result__isnull', True)), models.Q(('query__isnull', False), ('scope', 'query'), ('case__isnull', True), ('run__isnull', True), ('result__isnull', True)), models.Q(('result__isnull', False), ('scope', 'result'), ('case__isnull', True), ('run__isnull', True), ('query__isnull', True)), _connector='OR'), name='ck_review_note_scope_target'), models.CheckConstraint(condition=models.Q(('body__length__gte', 1), ('body__length__lte', 20000)), name='ck_review_note_body_length'), models.CheckConstraint(condition=models.Q(models.Q(('superseded_at__isnull', True), ('superseded_by__isnull', True)), models.Q(('superseded_at__isnull', False), ('superseded_by__isnull', False)), _connector='OR'), name='ck_review_note_supersession_paired'), models.CheckConstraint(condition=models.Q(('superseded_by__isnull', True), models.Q(('superseded_by', models.F('id')), _negated=True), _connector='OR'), name='ck_review_note_no_self_supersede')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('case', 'Case'), ('run', 'Run'), ('query', 'Query'), ('result', 'Result')], max_length=8)),
                ('value', models.SmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.case')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.query')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.result')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.run')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(condition=models.Q(('result__isnull', False)), fields=['result'], name='ix_review_rating_result')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('case__isnull', False), ('scope', 'case'), ('run__isnull', True), ('query__isnull', True), ('result__isnull', True)), models.Q(('run__isnull', False), ('scope', 'run'), ('case__isnull', True), ('query__isnull', True), ('result__isnull', True)), models.Q(('query__isnull', False), ('scope', 'query'), ('case__isnull', True), ('run__isnull', True), ('result__isnull', True)), models.Q(('result__isnull', False), ('scope', 'result'), ('case__isnull', True), ('run__isnull', True), ('query__isnull', True)), _connector='OR'), name='ck_review_rating_scope_target'), models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 5)), name='ck_review_rating_value_range'), models.UniqueConstraint(condition=models.Q(('scope', 'case')), fields=('case', 'author'), name='uq_review_rating_case_author'), models.UniqueConstraint(condition=models.Q(('scope', 'run')), fields=('run', 'author'), name='uq_review_rating_run_author'), models.UniqueConstraint(condition=models.Q(('scope', 'query')), fields=('query', 'author'), name='uq_review_rating_query_author'), models.UniqueConstraint(condition=models.Q(('scope', 'result')), fields=('result', 'author'), name='uq_review_rating_result_author')],
            },
        ),
        migrations.CreateModel(
            name='ResultOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField()),
                ('case', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='result_order', to='cases.case')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_orderings', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderings', to='cases.result')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'result'), name='uq_review_resultorder_case_result'), models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('case', 'position'), name='uq_review_resultorder_case_position')],
            },
        ),
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('case', 'Case'), ('run', 'Run'), ('query', 'Query'), ('result', 'Result')], max_length=8)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_assignments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.case')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.query')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.result')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='cases.run')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='review.tag')),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('case__isnull', False), ('scope', 'case'), ('run__isnull', True), ('query__isnull', True), ('result__isnull', True)), models.Q(('run__isnull', False), ('scope', 'run'), ('case__isnull', True), ('query__isnull', True), ('result__isnull', True)), models.Q(('query__isnull', False), ('scope', 'query'), ('case__isnull', True), ('run__isnull', True), ('result__isnull', True)), models.Q(('result__isnull', False), ('scope', 'result'), ('case__isnull', True), ('run__isnull', True), ('query__isnull', True)), _connector='OR'), name='ck_review_tagassignment_scope_target'), models.UniqueConstraint(condition=models.Q(('scope', 'case')), fields=('case', 'tag'), name='uq_review_tagassignment_case_tag'), models.UniqueConstraint(condition=models.Q(('scope', 'run')), fields=('run', 'tag'), name='uq_review_tagassignment_run_tag'), models.UniqueConstraint(condition=models.Q(('scope', 'query')), fields=('query', 'tag'), name='uq_review_tagassignment_query_tag'), models.UniqueConstraint(condition=models.Q(('scope', 'result')), fields=('result', 'tag'), name='uq_review_tagassignment_result_tag')],
            },
        ),
    ]
