# Generated by Django 5.2.17 on 2026-09-23 16:57

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('occurred_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('auth.login.succeeded', 'Login succeeded'), ('auth.login.failed', 'Login failed'), ('auth.logout', 'Logout'), ('auth.mfa.enrolled', 'Second factor enrolled'), ('auth.mfa.failed', 'Second factor failed'), ('auth.locked_out', 'Locked out'), ('auth.password.changed', 'Password changed'), ('authz.denied', 'Authorisation denied'), ('authz.role.changed', 'Role changed'), ('authz.membership.granted', 'Membership granted'), ('authz.membership.revoked', 'Membership revoked'), ('evidence.registered', 'Evidence registered'), ('evidence.accessed', 'Evidence accessed'), ('evidence.url.issued', 'Evidence URL issued'), ('evidence.processed', 'Evidence processed'), ('evidence.metadata.changed', 'Evidence metadata changed'), ('evidence.integrity.verified', 'Integrity verified'), ('evidence.integrity.failed', 'Integrity check failed'), ('evidence.quarantined', 'Evidence quarantined'), ('case.created', 'Case created'), ('case.status.changed', 'Case status changed'), ('case.metadata.changed', 'Case metadata changed'), ('case.owner.changed', 'Case owner changed'), ('search.run.created', 'Run created'), ('search.query.submitted', 'Query submitted'), ('search.results.viewed', 'Results viewed'), ('review.rating.recorded', 'Rating recorded'), ('review.note.recorded', 'Note recorded'), ('review.note.superseded', 'Note superseded'), ('review.approval.requested', 'Approval requested'), ('review.approval.decided', 'Approval decided'), ('review.approval.countersigned', 'Approval countersigned'), ('review.approval.withdrawn', 'Approval withdrawn'), ('export.requested', 'Export requested'), ('export.completed', 'Export completed'), ('export.failed', 'Export failed'), ('export.downloaded', 'Export downloaded'), ('admin.user.created', 'User created'), ('admin.user.deactivated', 'User deactivated'), ('admin.setting.changed', 'Setting changed'), ('admin.corpus.created', 'Corpus created'), ('admin.encoder.registered', 'Encoder registered'), ('audit.read', 'Audit trail read')], max_length=64)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_public_id', models.UUIDField(blank=True, null=True)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('correlation_id', models.UUIDField()),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('request_path', models.CharField(blank=True, default='', max_length=300)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=16)),
                ('detail', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['actor', 'action', '-occurred_at'], name='ix_audit_auditevent_actor_action_time'), models.Index(fields=['target_type', 'target_public_id', '-occurred_at'], name='ix_audit_auditevent_target'), models.Index(fields=['action', '-occurred_at'], name='ix_audit_auditevent_action_time'), models.Index(fields=['correlation_id'], name='ix_audit_auditevent_correlation'), models.Index(fields=['-occurred_at'], name='ix_audit_auditevent_occurred_at')],
                'constraints': [models.UniqueConstraint(fields=('public_id',), name='uq_audit_auditevent_public_id'), models.CheckConstraint(condition=models.Q(('action__in', ['auth.login.succeeded', 'auth.login.failed', 'auth.logout', 'auth.mfa.enrolled', 'auth.mfa.failed', 'auth.locked_out', 'auth.password.changed', 'authz.denied', 'authz.role.changed', 'authz.membership.granted', 'authz.membership.revoked', 'evidence.registered', 'evidence.accessed', 'evidence.url.issued', 'evidence.processed', 'evidence.metadata.changed', 'evidence.integrity.verified', 'evidence.integrity.failed', 'evidence.quarantined', 'case.created', 'case.status.changed', 'case.metadata.changed', 'case.owner.changed', 'search.run.created', 'search.query.submitted', 'search.results.viewed', 'review.rating.recorded', 'review.note.recorded', 'review.note.superseded', 'review.approval.requested', 'review.approval.decided', 'review.approval.countersigned', 'review.approval.withdrawn', 'export.requested', 'export.completed', 'export.failed', 'export.downloaded', 'admin.user.created', 'admin.user.deactivated', 'admin.setting.changed', 'admin.corpus.created', 'admin.encoder.registered', 'audit.read'])), name='ck_audit_auditevent_action_valid'), models.CheckConstraint(condition=models.Q(('outcome__in', ['succeeded', 'denied', 'failed'])), name='ck_audit_auditevent_outcome_valid'), models.CheckConstraint(condition=models.Q(('actor__isnull', False), models.Q(('actor_username', ''), _negated=True), _connector='OR'), name='ck_audit_auditevent_actor_identified')],
            },
        ),
    ]
