# Generated by Django 5.2.17 on 2026-09-17 04:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('username', models.CharField(help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('investigator', 'Investigator'), ('analyst', 'Analyst'), ('reviewer', 'Reviewer'), ('auditor', 'Auditor')], default='analyst', max_length=20)),
                ('mfa_enforced', models.BooleanField(default=False)),
                ('mfa_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['role'], name='ix_accounts_user_role_active')],
                'constraints': [models.UniqueConstraint(fields=('username',), name='uq_accounts_user_username'), models.UniqueConstraint(fields=('public_id',), name='uq_accounts_user_public_id'), models.CheckConstraint(condition=models.Q(('role__in', ['administrator', 'investigator', 'analyst', 'reviewer', 'auditor'])), name='ck_accounts_user_role_valid'), models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['administrator', 'investigator', 'reviewer']), _negated=True), ('mfa_enforced', True), _connector='OR'), name='ck_accounts_user_mfa_required_roles'), models.CheckConstraint(condition=models.Q(('mfa_confirmed_at__isnull', True), ('mfa_enforced', True), _connector='OR'), name='ck_accounts_user_mfa_confirmed_state')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
