# Generated by Django 5.2.17 on 2026-09-23 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), default=uuid.uuid4, editable=False)),
                ('task_name', models.CharField(max_length=200)),
                ('celery_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('phase', models.CharField(blank=True, default='', max_length=50)),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField()),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField()),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_public_id', models.UUIDField(blank=True, null=True)),
                ('error_class', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status__in', ['queued', 'started', 'retrying'])), fields=['status', 'queued_at'], name='ix_tasks_taskrun_status_queued'), models.Index(fields=['correlation_id'], name='ix_tasks_taskrun_correlation'), models.Index(fields=['celery_task_id'], name='ix_tasks_taskrun_celery_task_id'), models.Index(fields=['requested_by', '-queued_at'], name='ix_tasks_taskrun_requested_by_time')],
                'constraints': [models.UniqueConstraint(fields=('idempotency_key',), name='uq_tasks_taskrun_idempotency_key'), models.UniqueConstraint(fields=('public_id',), name='uq_tasks_taskrun_public_id'), models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'started', 'retrying', 'succeeded', 'failed', 'cancelled'])), name='ck_tasks_taskrun_status_valid'), models.CheckConstraint(condition=models.Q(('progress_current__gte', 0), models.Q(('progress_total__isnull', True), ('progress_total__gte', models.F('progress_current')), _connector='OR')), name='ck_tasks_taskrun_progress_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['succeeded', 'failed', 'cancelled']), _negated=True), ('finished_at__isnull', False), _connector='OR'), name='ck_tasks_taskrun_terminal_finished')],
            },
        ),
    ]
