# Generated by Django 5.2.17 on 2026-09-23 15:56

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Declared by hand and not by `makemigrations`, which has no way to know that a
        # `VectorField` needs an extension. Without it the two are unordered, and this migration
        # applied first fails on `type "vector" does not exist` (see `common/0001_extensions.py`).
        ('common', '0001_extensions'),
        ('datasets', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(choices=[('clip', 'CLIP'), ('dinov2', 'DINOv2')], max_length=16)),
                ('version', models.CharField(max_length=50)),
                ('preprocess_version', models.CharField(max_length=50)),
                ('dimensions', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'version', 'preprocess_version'), name='uq_search_encoder_identity'), models.CheckConstraint(condition=models.Q(('family__in', ['clip', 'dinov2'])), name='ck_search_encoder_family_valid'), models.CheckConstraint(condition=models.Q(models.Q(('dimensions', 512), ('family', 'clip')), models.Q(('dimensions', 384), ('family', 'dinov2')), _connector='OR'), name='ck_search_encoder_dimensions_match_family')],
            },
        ),
        migrations.CreateModel(
            name='Dinov2Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encoded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('content', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='datasets.contentobject')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tasks.taskrun')),
                ('encoder', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='search.encoder')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['encoder'], name='ix_search_dinov2embedding_encoder')],
                'constraints': [models.UniqueConstraint(fields=('content', 'encoder'), name='uq_search_dinov2embedding_content_encoder')],
            },
        ),
        migrations.CreateModel(
            name='ClipEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encoded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('content', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='datasets.contentobject')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tasks.taskrun')),
                ('encoder', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='search.encoder')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['encoder'], name='ix_search_clipembedding_encoder')],
                'constraints': [models.UniqueConstraint(fields=('content', 'encoder'), name='uq_search_clipembedding_content_encoder')],
            },
        ),
        migrations.CreateModel(
            name='AnnIndexBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_table', models.CharField(max_length=63)),
                ('method', models.CharField(default='hnsw', max_length=16)),
                ('m', models.IntegerField()),
                ('ef_construction', models.IntegerField()),
                ('ef_search', models.IntegerField()),
                ('row_count_at_build', models.BigIntegerField()),
                ('built_at', models.DateTimeField()),
                ('build_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('measured_recall', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('recall_k', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('encoder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index_builds', to='search.encoder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('measured_recall__isnull', True), models.Q(('measured_recall__gte', 0), ('measured_recall__lte', 1)), _connector='OR'), name='ck_search_annindexbuild_recall_range'), models.CheckConstraint(condition=models.Q(models.Q(('measured_recall__isnull', True), ('recall_k__isnull', True)), models.Q(('measured_recall__isnull', False), ('recall_k__isnull', False)), _connector='OR'), name='ck_search_annindexbuild_recall_paired')],
            },
        ),
    ]
